[package]
name = "hello_rust"
version = "0.1.0"
authors = ["Desire Kaleba <desirekaleba@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
path = "main.rs"
